### ISSUE TITLE
Directory structure being flattened

### ISSUE THREAD

**Issue by nkabrich** [yogthos/asset-minifier#14]
Right now if `source` is a directory with subdirectories, the subdirectory structure will not be preserved in  `target`.  Would it make sense to preserve any subdirectory structure in the `target` directory? The current behavior runs the risk of files in subdirectories overwriting identically-named files in a parent directory (in the `target` directory).

Otherwise, it would be nice to be able to disallow this recursive behavior, giving the user the chance to handle subdirectories with multiple calls to `minify`.

I am actually having this problem with the lein-asset-minifier project, but I'm guessing this is the appropriate place for the issue.  If you you think either of these should be implemented but don't have the time to do it yourself, I'd be happy to help.

**Comment by yogthos** [comment]
I think that preserving the structure would make sense, and I'd be glad to take a PR if you have a chance to work on this.
