### ISSUE TITLE
setting language-out option

### ISSUE THREAD

**Issue by rangeoshun** [yogthos/asset-minifier#17]
I need to transpile a package from ES6 to ES5 in cljsjs/packages, which uses `asset-minifier.core/minify-js` to do minifications. Currently this is not possible as `LANGUAGE_OUT` arg cannot be set, and hence this error:

```
ES6 is only supported for transpilation to a lower ECMAScript version. Set --language_out to ES3, ES5, or ES5_STRICT.
```

Any ideas or thought, or shall I just create a PR? I'd gladly do that BTW.

Cheers!

**Comment by yogthos** [comment]
Hi, a PR would be very much appreciated. :)

**Comment by rangeoshun** [comment]
Sorry... closed by mistake.

**Comment by rangeoshun** [comment]
You up for a breaking change? The parameter `language` kinda lacks descriptiveness. If we introduce `language-out` it should be `language-in` instead.

**Comment by yogthos** [comment]
Yeah I think that's a good call as it makes things more explicit. Would you mind taking a look at [lein-asset-minifier](https://github.com/yogthos/lein-asset-minifier) plugin as well to make sure it's inline with the change.

**Comment by rangeoshun** [comment]
Check, and I think all's good. The interface was extended and the `language` option wasn't in the docs.

**Comment by yogthos** [comment]
👍
