### ISSUE TITLE
Add HTML minification

### ISSUE THREAD

**Issue by pandeiro** [yogthos/asset-minifier#3]
In addition to CSS and JS, HTML can also be minified to reduce the size of assets that need to be sent over the wire.

There is an existent library for the JVM that does that well: [htmlcompressor](https://code.google.com/p/htmlcompressor/). Example Clojure use of this can be found [here](https://gist.github.com/pandeiro/a814a1012698c007e10a).

Would you accept a PR for this? Any additional thoughts?

**Comment by Atsman** [comment]
@pandeiro and where are your results? I am looking for this feature right now...

**Comment by Atsman** [comment]
@yogthos Do you have any suggestions on how minify function should look like? I mean to support also folder to folder html compression. I have already created an interop Clojure library for htmlcompressor [clj-html-compressor](https://github.com/Atsman/clj-html-compressor) and now work on integration to asset-minifier. 

```clojure
(minify {:html {:source "src/html" :output "target/assets/html"}
              :js {:source "src/js" :output "target/assets/js/site.min.js"}
              :css {:source "src/css" :output "target/assets/css/site.min.css"}})
```

and more generic variants

(minify {:html [{:source "src/html" :output "target/assets/html"}
                         {:source "src/html2" :output "target/assets/html2"}]
              :js {:source "src/js" :output "target/assets/js/site.min.js"}
              :css {:source "src/css" :output "target/assets/css/site.min.css"}})

Any suggestions? That require breaking changes to be made... i need your advice

**Comment by yogthos** [comment]
Using a map seems reasonable. It would probably make sense to use a multimethod to select the minifier based on the key. So, then the `minify` function could go through the key/value pairs in the map and run the appropriate minifier for each type.

**Comment by Atsman** [comment]
https://github.com/yogthos/asset-minifier/pull/11

**Comment by Atsman** [comment]
@yogthos hi, i think we can close this issue!

**Comment by yogthos** [comment]
👍
