### ISSUE TITLE
setting language-in option

### ISSUE THREAD

**Issue by shaunlebron** [yogthos/asset-minifier#6]
there is a minify task in boot-cljsjs that uses `minify-js`.  Being able to set the closure compiler option for "language-in" to ECMASCRIPT5 will help us prevent "trailing comma" errors when minifying some cljsjs-packages that are auto-built.

I can create the PR; just let me know if you have thoughts on it.  thanks

**Comment by martinklepsch** [comment]
:+1: @yogthos any objections?

**Comment by yogthos** [comment]
@shaunlebron , @martinklepsch  yeah that sounds great to me :)

**Comment by SerCeMan** [comment]
Is there any results? Have the same problem with lein-asset-minifier, 
```
errors:
 JSC_TRAILING_COMMA. Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option. at assets/js/hterm.js line 265 : 26
```

**Comment by yogthos** [comment]
closed by https://github.com/yogthos/asset-minifier/pull/7
