### ISSUE TITLE
Charset exceptions

### ISSUE THREAD

**Issue by rredpoppy** [yogthos/asset-minifier#9]
I am getting this exception when using minify-js:
`java.lang.String cannot be cast to java.nio.charset.Charset`

on a side note: why use such an old closure compiler?

**Comment by yogthos** [comment]
The compiler should be updated, simply haven't looked at it in a while.

**Comment by tuhlmann** [comment]
I'm getting the same exception since updating asset-minifier to 0.2.1 (was: 0.2.0):

ClassCastException sun.nio.cs.UTF_8 cannot be cast to java.lang.String  asset-minifier.core/compile-js
 (core.clj:91)

**Comment by yogthos** [comment]
Maybe there's something on the classpath that's causing an older dependency to be pulled in. The lein plugin hasn't been updated to the new version however, so it still has the old behavior.

**Comment by tuhlmann** [comment]
I was using Closurescript 1.8.40, that was probably adding an older version of the Closure compiler. I updated to the latest 1.9 version, and with that asset-minifier 0.2.0 didn't work anymore, but 0.2.1 does.

It appears that 0.2.1 only works with Clojurescript 1.9.x while 0.2.0 only works for cljs 1.8.

In any case, mystery solved...

**Comment by yogthos** [comment]
Ah good to know, I'll add a note in the readme regarding that then.
